### ISSUE TITLE
Blender plugin not working

### ISSUE THREAD

**Issue by PanekPro** [OpenNaja/cobra-tools#105]
When I try to import the blender plugin as an addon, it doesnt work. I have blender 2.92 and tried to install the version it the page Blender Plugin How To Use. This is  what it said: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\...\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\cobra-tools-master\__init__.py", line 24, in <module>
    from plugin.modules_import.hair import vcol_to_comb, comb_to_vcol
ModuleNotFoundError: No module named 'plugin.modules_import.hair'
I tried to look at old issues, but nothing helped. What should i do?

**Comment by HENDRIX-ZT2** [comment]
It's a version conflict. Delete all old copies of the tools from all older blender addon folders.
