### ISSUE TITLE
Support for Thrillvill Off the Rails (2007)

### ISSUE THREAD

**Issue by Howl22** [OpenNaja/cobra-tools#132]
**Describe the bug**
ovl file from Thrillvill Off the Rails causes ovl_tool_gui.py to crash

**To Reproduce**
1. double click ovl_tool_gui.py
2. set game as unknown game 
3. Explorervill.ovl from Thrillville Off the Rails
  - ovl extracted from .zap file using this bms script http://wiki.xentax.com/index.php/Frontier_Developments_ZAP 
4. output shows error "unpack requires a buffer of 4 bytes"

**Expected behavior**
expect extract of ovl artifacts  

**Version Info:**
 - Python Version: Python 3.9.6
 - Blender Version: blender 2.93.3
 - Cobra Tools Version 2.3.7
 
 **Log Files:**
INFO | Running python 3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)]
INFO | Running cobra-tools 2.3.6
config.ini is missing or broken!
INFO | Loading hash table...
INFO | Loaded 272535 hash - name pairs in 0.18 seconds.
INFO | Loading Explorerville.ovl
Traceback (most recent call last):
  File "C:\Users\howl\Downloads\cobra-tools-master\cobra-tools-master\ovl_tool_gui.py", line 302, in load
    self.ovl_data.load(self.file_widget.filepath, commands=self.commands, hash_table=self.hash_table)
  File "C:\Users\howl\Downloads\cobra-tools-master\cobra-tools-master\generated\formats\ovl\__init__.py", line 1070, in load
    self.eof = super().load(filepath)
  File "C:\Users\howl\Downloads\cobra-tools-master\cobra-tools-master\generated\io.py", line 253, in load
    self.read(stream)
  File "C:\Users\howl\Downloads\cobra-tools-master\cobra-tools-master\generated\formats\ovl\compound\Header.py", line 174, in read
    self.archives.read(stream, ArchiveEntry, self.num_archives, None)
  File "C:\Users\howl\Downloads\cobra-tools-master\cobra-tools-master\generated\array.py", line 46, in read
    self.extend([rfunc() for _ in range(self.arr1)])
  File "C:\Users\howl\Downloads\cobra-tools-master\cobra-tools-master\generated\array.py", line 46, in <listcomp>
    self.extend([rfunc() for _ in range(self.arr1)])
  File "C:\Users\howl\Downloads\cobra-tools-master\cobra-tools-master\generated\array.py", line 26, in func
    return stream.read_type(self.dtype, (self.arg, self.template))
  File "C:\Users\howl\Downloads\cobra-tools-master\cobra-tools-master\generated\io.py", line 193, in read_type
    obj.read(self)
  File "C:\Users\howl\Downloads\cobra-tools-master\cobra-tools-master\generated\formats\ovl\compound\ArchiveEntry.py", line 76, in read
    self.ovs_file_offset = stream.read_uint()
  File "C:\Users\howl\Downloads\cobra-tools-master\cobra-tools-master\generated\io.py", line 151, in read_value
    return unpack(read(size))[0]
struct.error: unpack requires a buffer of 4 bytes

*Note*
I can upload the ovl file if necessary

**Comment by HENDRIX-ZT2** [comment]
Closed due to inactivity and scope.
