### ISSUE TITLE
AttributeError: 'int' object has no attribute '_value'

### ISSUE THREAD

**Issue by magicdog2013games** [OpenNaja/cobra-tools#136]
the switch says something about absoluterror but it's too fast for me to read. the opening folder thing I tried to fix by reinstalling since it worked for me last time but it didn't this time

Update:
I got the error code in time
INFO | Running python 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)]
INFO | Running cobra-tools 2.3.8
INFO | Loading hash table...
INFO | Loaded 272535 hash - name pairs in 0.18 seconds.
Traceback (most recent call last):
  File "C:\Users\User\Desktop\Desktop Stuff\cobra-tools-master\ovl_tool_gui.py", line 190, in game_changed
    set_game(self.ovl_data.context, game)
  File "C:\Users\User\Desktop\Desktop Stuff\cobra-tools-master\generated\formats\ovl\versions.py", line 92, in set_game
    return set_pz16(context)
  File "C:\Users\User\Desktop\Desktop Stuff\cobra-tools-master\generated\formats\ovl\versions.py", line 48, in set_pz16
    context.user_version._value = 8340
AttributeError: 'int' object has no attribute '_value'

**Comment by magicdog2013games** [comment]
I got the error code in time
INFO | Running python 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)]
INFO | Running cobra-tools 2.3.8
INFO | Loading hash table...
INFO | Loaded 272535 hash - name pairs in 0.18 seconds.
Traceback (most recent call last):
  File "C:\Users\User\Desktop\Desktop Stuff\cobra-tools-master\ovl_tool_gui.py", line 190, in game_changed
    set_game(self.ovl_data.context, game)
  File "C:\Users\User\Desktop\Desktop Stuff\cobra-tools-master\generated\formats\ovl\versions.py", line 92, in set_game
    return set_pz16(context)
  File "C:\Users\User\Desktop\Desktop Stuff\cobra-tools-master\generated\formats\ovl\versions.py", line 48, in set_pz16
    context.user_version._value = 8340
AttributeError: 'int' object has no attribute '_value'
