### ISSUE TITLE
I import When MS2 files, I will be prompted with "bone info failed". I can't import any objects. What's the problem?

### ISSUE THREAD

**Issue by LGGHC** [OpenNaja/cobra-tools#173]
I import When MS2 files, I will be prompted with "Bone info 0 failed
. I can't import any objects. What's the problem?

**Comment by HENDRIX-ZT2** [comment]
You.
You haven't provided a log file, or the file you're trying to import, or clarified you're using current master for extraction and as the plugin.

**Comment by LGGHC** [comment]
> You. You haven't provided a log file, or the file you're trying to import, or clarified you're using current master for extraction and as the plugin.
Is this the log file?
Read prefs: C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\config\userpref.blend
[io_pdx_mesh] INFO:  Running from e:\steamlibrary\steamapps\common\blender\blender.exe
[io_pdx_mesh] INFO:  C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_pdx_mesh
[io_pdx_mesh] INFO:  Skipped update check. (already ran today)
[io_pdx_mesh] INFO:  Loading Blender UI.
hello kumopult!
mmd_tools registed 140 classes
xps_tools updater verbose is enabled
xps_tools Updater: Read in JSON settings from file
2.93
Files Should be Exporting to : C:\Users\Administrator\Documents\DAZ 3D\Bridges\Daz To Blender\Exports
register
hello kumopult!
Registered Animation Nodes
[root] INFO:  Running python 3.9.2 (default, Mar  1 2021, 08:18:55) [MSC v.1916 64 bit (AMD64)]
INFO | Running python 3.9.2 (default, Mar  1 2021, 08:18:55) [MSC v.1916 64 bit (AMD64)]
[root] INFO:  Running cobra-tools 2.3.8
INFO | Running cobra-tools 2.3.8
libpng warning: iCCP: cHRM chunk does not match sRGB
淇℃伅: 宸插垹闄?3 涓墿浣?
[root] DEBUG:  Reading D:\ZOOM\新建文件夹 (5)\bonobo_male_.ms2
[root] DEBUG:  Reading bone info
[root] DEBUG:  BONE INFO 0 starts at 5811
[root] ERROR:  Got exception on main handler
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\formats\ms2\compound\ModelReader.py", line 74, in read
    i = self.assign_bone_info(i, model_info, stream)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\formats\ms2\compound\ModelReader.py", line 82, in assign_bone_info
    model_info.bone_info = self.read_bone_info(stream, i)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\formats\ms2\compound\ModelReader.py", line 107, in read_bone_info
    bone_info.read(stream)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\formats\ms2\compound\BoneInfo.py", line 232, in read
    self.joints = stream.read_type(JointData, (self.context, None, None))
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\io.py", line 145, in read_type
    obj.read(self)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\formats\ms2\compound\JointData.py", line 195, in read
    self.joint_infos.read(stream, JointInfo, self.joint_count, None)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\array.py", line 49, in read
    self.extend([rfunc() for _ in range(self.arr1)])
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\array.py", line 49, in <listcomp>
    self.extend([rfunc() for _ in range(self.arr1)])
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\array.py", line 29, in func
    return stream.read_type(self.dtype, (self.context, self.arg, self.template))
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\io.py", line 145, in read_type
    obj.read(self)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\formats\ms2\compound\JointInfo.py", line 36, in read
    self.hitchecks.read(stream, HitCheckEntry, self.hitcheck_count, None)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\array.py", line 49, in read
    self.extend([rfunc() for _ in range(self.arr1)])
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\array.py", line 49, in <listcomp>
    self.extend([rfunc() for _ in range(self.arr1)])
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\array.py", line 29, in func
    return stream.read_type(self.dtype, (self.context, self.arg, self.template))
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\io.py", line 145, in read_type
    obj.read(self)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\formats\ms2\compound\HitCheckEntry.py", line 81, in read
    self.type = CollisionType(stream.read_uint())
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\base_enum.py", line 12, in __call__
    return super().__call__(value, *args, **kwargs)
  File "E:\SteamLibrary\steamapps\common\Blender\2.93\python\lib\enum.py", line 360, in __call__
    return cls.__new__(cls, value)
  File "E:\SteamLibrary\steamapps\common\Blender\2.93\python\lib\enum.py", line 677, in __new__
    raise ve_exc
ValueError: 2147483648 is not a valid CollisionType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\__init__.py", line 46, in handle_errors
    for msg in func(**kwargs):
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\plugin\import_ms2.py", line 21, in load
    ms2.load(filepath, read_editable=True)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\formats\ms2\__init__.py", line 79, in load
    self.read(stream)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\formats\ms2\compound\Ms2InfoHeader.py", line 69, in read
    self.models_reader = stream.read_type(ModelReader, (self.context, self.model_infos, None))
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\io.py", line 145, in read_type
    obj.read(self)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\formats\ms2\compound\ModelReader.py", line 76, in read
    raise AttributeError(f"Bone info {i} failed")
AttributeError: Bone info 0 failed
ERROR | Got exception on main handler
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\formats\ms2\compound\ModelReader.py", line 74, in read
    i = self.assign_bone_info(i, model_info, stream)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\formats\ms2\compound\ModelReader.py", line 82, in assign_bone_info
    model_info.bone_info = self.read_bone_info(stream, i)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\formats\ms2\compound\ModelReader.py", line 107, in read_bone_info
    bone_info.read(stream)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\formats\ms2\compound\BoneInfo.py", line 232, in read
    self.joints = stream.read_type(JointData, (self.context, None, None))
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\io.py", line 145, in read_type
    obj.read(self)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\formats\ms2\compound\JointData.py", line 195, in read
    self.joint_infos.read(stream, JointInfo, self.joint_count, None)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\array.py", line 49, in read
    self.extend([rfunc() for _ in range(self.arr1)])
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\array.py", line 49, in <listcomp>
    self.extend([rfunc() for _ in range(self.arr1)])
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\array.py", line 29, in func
    return stream.read_type(self.dtype, (self.context, self.arg, self.template))
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\io.py", line 145, in read_type
    obj.read(self)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\formats\ms2\compound\JointInfo.py", line 36, in read
    self.hitchecks.read(stream, HitCheckEntry, self.hitcheck_count, None)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\array.py", line 49, in read
    self.extend([rfunc() for _ in range(self.arr1)])
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\array.py", line 49, in <listcomp>
    self.extend([rfunc() for _ in range(self.arr1)])
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\array.py", line 29, in func
    return stream.read_type(self.dtype, (self.context, self.arg, self.template))
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\io.py", line 145, in read_type
    obj.read(self)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\formats\ms2\compound\HitCheckEntry.py", line 81, in read
    self.type = CollisionType(stream.read_uint())
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\base_enum.py", line 12, in __call__
    return super().__call__(value, *args, **kwargs)
  File "E:\SteamLibrary\steamapps\common\Blender\2.93\python\lib\enum.py", line 360, in __call__
    return cls.__new__(cls, value)
  File "E:\SteamLibrary\steamapps\common\Blender\2.93\python\lib\enum.py", line 677, in __new__
    raise ve_exc
ValueError: 2147483648 is not a valid CollisionType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\__init__.py", line 46, in handle_errors
    for msg in func(**kwargs):
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\plugin\import_ms2.py", line 21, in load
    ms2.load(filepath, read_editable=True)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\formats\ms2\__init__.py", line 79, in load
    self.read(stream)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\formats\ms2\compound\Ms2InfoHeader.py", line 69, in read
    self.models_reader = stream.read_type(ModelReader, (self.context, self.model_infos, None))
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\io.py", line 145, in read_type
    obj.read(self)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\formats\ms2\compound\ModelReader.py", line 76, in read
    raise AttributeError(f"Bone info {i} failed")
AttributeError: Bone info 0 failed

**Comment by LGGHC** [comment]
And this, the log in the plug-in folder
INFO | Running python 3.9.2 (default, Mar  1 2021, 08:18:55) [MSC v.1916 64 bit (AMD64)]
INFO | Running cobra-tools 2.3.8
DEBUG | Reading D:\ZOOM\新建文件夹 (5)\bonobo_male_.ms2
DEBUG | Reading bone info
DEBUG | BONE INFO 0 starts at 5811
ERROR | Got exception on main handler
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\formats\ms2\compound\ModelReader.py", line 74, in read
    i = self.assign_bone_info(i, model_info, stream)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\formats\ms2\compound\ModelReader.py", line 82, in assign_bone_info
    model_info.bone_info = self.read_bone_info(stream, i)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\formats\ms2\compound\ModelReader.py", line 107, in read_bone_info
    bone_info.read(stream)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\formats\ms2\compound\BoneInfo.py", line 232, in read
    self.joints = stream.read_type(JointData, (self.context, None, None))
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\io.py", line 145, in read_type
    obj.read(self)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\formats\ms2\compound\JointData.py", line 195, in read
    self.joint_infos.read(stream, JointInfo, self.joint_count, None)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\array.py", line 49, in read
    self.extend([rfunc() for _ in range(self.arr1)])
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\array.py", line 49, in <listcomp>
    self.extend([rfunc() for _ in range(self.arr1)])
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\array.py", line 29, in func
    return stream.read_type(self.dtype, (self.context, self.arg, self.template))
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\io.py", line 145, in read_type
    obj.read(self)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\formats\ms2\compound\JointInfo.py", line 36, in read
    self.hitchecks.read(stream, HitCheckEntry, self.hitcheck_count, None)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\array.py", line 49, in read
    self.extend([rfunc() for _ in range(self.arr1)])
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\array.py", line 49, in <listcomp>
    self.extend([rfunc() for _ in range(self.arr1)])
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\array.py", line 29, in func
    return stream.read_type(self.dtype, (self.context, self.arg, self.template))
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\io.py", line 145, in read_type
    obj.read(self)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\formats\ms2\compound\HitCheckEntry.py", line 81, in read
    self.type = CollisionType(stream.read_uint())
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\base_enum.py", line 12, in __call__
    return super().__call__(value, *args, **kwargs)
  File "E:\SteamLibrary\steamapps\common\Blender\2.93\python\lib\enum.py", line 360, in __call__
    return cls.__new__(cls, value)
  File "E:\SteamLibrary\steamapps\common\Blender\2.93\python\lib\enum.py", line 677, in __new__
    raise ve_exc
ValueError: 2147483648 is not a valid CollisionType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\__init__.py", line 46, in handle_errors
    for msg in func(**kwargs):
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\plugin\import_ms2.py", line 21, in load
    ms2.load(filepath, read_editable=True)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\formats\ms2\__init__.py", line 79, in load
    self.read(stream)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\formats\ms2\compound\Ms2InfoHeader.py", line 69, in read
    self.models_reader = stream.read_type(ModelReader, (self.context, self.model_infos, None))
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\io.py", line 145, in read_type
    obj.read(self)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\formats\ms2\compound\ModelReader.py", line 76, in read
    raise AttributeError(f"Bone info {i} failed")
AttributeError: Bone info 0 failed

**Comment by LGGHC** [comment]
> You. You haven't provided a log file, or the file you're trying to import, or clarified you're using current master for extraction and as the plugin.

And this, the log in the plug-in folder
INFO | Running python 3.9.2 (default, Mar  1 2021, 08:18:55) [MSC v.1916 64 bit (AMD64)]
INFO | Running cobra-tools 2.3.8
DEBUG | Reading D:\ZOOM\新建文件夹 (5)\bonobo_male_.ms2
DEBUG | Reading bone info
DEBUG | BONE INFO 0 starts at 5811
ERROR | Got exception on main handler
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\formats\ms2\compound\ModelReader.py", line 74, in read
    i = self.assign_bone_info(i, model_info, stream)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\formats\ms2\compound\ModelReader.py", line 82, in assign_bone_info
    model_info.bone_info = self.read_bone_info(stream, i)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\formats\ms2\compound\ModelReader.py", line 107, in read_bone_info
    bone_info.read(stream)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\formats\ms2\compound\BoneInfo.py", line 232, in read
    self.joints = stream.read_type(JointData, (self.context, None, None))
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\io.py", line 145, in read_type
    obj.read(self)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\formats\ms2\compound\JointData.py", line 195, in read
    self.joint_infos.read(stream, JointInfo, self.joint_count, None)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\array.py", line 49, in read
    self.extend([rfunc() for _ in range(self.arr1)])
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\array.py", line 49, in <listcomp>
    self.extend([rfunc() for _ in range(self.arr1)])
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\array.py", line 29, in func
    return stream.read_type(self.dtype, (self.context, self.arg, self.template))
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\io.py", line 145, in read_type
    obj.read(self)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\formats\ms2\compound\JointInfo.py", line 36, in read
    self.hitchecks.read(stream, HitCheckEntry, self.hitcheck_count, None)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\array.py", line 49, in read
    self.extend([rfunc() for _ in range(self.arr1)])
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\array.py", line 49, in <listcomp>
    self.extend([rfunc() for _ in range(self.arr1)])
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\array.py", line 29, in func
    return stream.read_type(self.dtype, (self.context, self.arg, self.template))
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\io.py", line 145, in read_type
    obj.read(self)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\formats\ms2\compound\HitCheckEntry.py", line 81, in read
    self.type = CollisionType(stream.read_uint())
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\base_enum.py", line 12, in __call__
    return super().__call__(value, *args, **kwargs)
  File "E:\SteamLibrary\steamapps\common\Blender\2.93\python\lib\enum.py", line 360, in __call__
    return cls.__new__(cls, value)
  File "E:\SteamLibrary\steamapps\common\Blender\2.93\python\lib\enum.py", line 677, in __new__
    raise ve_exc
ValueError: 2147483648 is not a valid CollisionType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\__init__.py", line 46, in handle_errors
    for msg in func(**kwargs):
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\plugin\import_ms2.py", line 21, in load
    ms2.load(filepath, read_editable=True)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\formats\ms2\__init__.py", line 79, in load
    self.read(stream)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\formats\ms2\compound\Ms2InfoHeader.py", line 69, in read
    self.models_reader = stream.read_type(ModelReader, (self.context, self.model_infos, None))
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\io.py", line 145, in read_type
    obj.read(self)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cobra-tools-master\generated\formats\ms2\compound\ModelReader.py", line 76, in read
    raise AttributeError(f"Bone info {i} failed")
AttributeError: Bone info 0 failed

**Comment by LGGHC** [comment]
https://drive.google.com/file/d/1GcWtbRqN2uD1yZsbDhs58FKObfBaczGk/view?usp=sharing 
I need to import Blender's file

**Comment by HENDRIX-ZT2** [comment]
Works just fine. Extracted with current master, imports with current master.
![grafik](https://user-images.githubusercontent.com/28632661/154501274-373be080-8aa6-4fa2-a451-55211adb8198.png)
[bonobo_male_.zip](https://github.com/OpenNaja/cobra-tools/files/8089322/bonobo_male_.zip)

**Comment by LGGHC** [comment]
> Works just fine. Extracted with current master, imports with current master. ![grafik](https://user-images.githubusercontent.com/28632661/154501274-373be080-8aa6-4fa2-a451-55211adb8198.png) [bonobo_male_.zip](https://github.com/OpenNaja/cobra-tools/files/8089322/bonobo_male_.zip)

I can import the file you provided in blender. Does this mean that I made an error in unpacking the OVL file?
