### ISSUE TITLE
Warhammer support

### ISSUE THREAD

**Issue by 1756816846** [OpenNaja/cobra-tools#337]
vers1111111111111111111ion: 53
ERROR | An exception occurred while extracting annihilator_warhammer_.ms2
Traceback (most recent call last):
  File "K:\SteamLibrary\steamapps\common\Warhammer Age of Sigmar - Realms of Ruin - Beta\Win64\cobra-tools-master\generated\formats\ovl\__init__.py", line 594, in extract
    ret_paths = loader.extract(out_dir_func)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\SteamLibrary\steamapps\common\Warhammer Age of Sigmar - Realms of Ruin - Beta\Win64\cobra-tools-master\modules\formats\MS2.py", line 261, in extract
    for wrapper in model_info.meshes.data:
TypeError: 'NoneType' object is not iterable

**Comment by HENDRIX-ZT2** [comment]
If you want us to investigate this, upload an ovl file (and associated ovs files) that causes the error.

**Comment by 1756816846** [comment]
> If you want us to investigate this, upload an ovl file (and associated ovs files) that causes the error.

file：https://anonfiles.com/w7c34a14z7/Annihilator_ovl
game:Warhammer Age of Sigmar - Realms of Ruin - Beta

**Comment by HENDRIX-ZT2** [comment]
Models, materials, textures appear to be fine. Please report if you find something that does not work.

**Comment by 1756816846** [comment]
How did you set it up



> Models, materials, textures appear to be fine. Please report if you find something that does not work.

**Comment by 1756816846** [comment]
![image](https://github.com/OpenNaja/cobra-tools/assets/22480057/c4ca6333-0132-4d15-9468-33c912a218a4)

**Comment by 1756816846** [comment]
good job，thank you
![image](https://github.com/OpenNaja/cobra-tools/assets/22480057/532f71a1-969e-434b-b9f7-b60f9cf6304a)
