### ISSUE TITLE
No Module Named Pyffi

### ISSUE THREAD

**Issue by AgentiumGamer** [OpenNaja/cobra-tools#52]
Have everything installed and I'm able to unpack my OVL. files but once I go to import the .mdl2 into Blender I encounter this error. 

Traceback (most recent call last):
  File "C:\Users\_____\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\cobra-blender\__init__.py", line 68, in execute from . import import_mdl2
  File "C:\Users\_____\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\cobra-blender\import_mdl2.py", line 12, in <module>
    from .pyffi_ext.formats.ms2 import Ms2Format
  File "C:\Users\_____\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\cobra-blender\pyffi_ext\formats\ms2\__init__.py", line 46, in <module>
    import pyffi.object_models.xml
ModuleNotFoundError: No module named 'pyffi'

location: <unknown location>:-1

I have little coding experience, went through the install instructions exactly and uninstalled and reinstalled multiple times. Any help would be appreciated.

**Comment by HENDRIX-ZT2** [comment]
You did not install pyffi to blender's python folder.

**Comment by AgentiumGamer** [comment]
> You did not install pyffi to blender's python folder.

Anything you can link with better instructions then because the sites I've been to I follow the instructions but end up with the same outcome and that doesn't really tell me a lot. Thanks.
