### ISSUE TITLE
Getting this error while importing .mdl2 file in blender

### ISSUE THREAD

**Issue by affaf** [OpenNaja/cobra-tools#59]
Traceback (most recent call last):
  File "C:\Users\Affaf\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\cobra-blender\__init__.py", line 70, in execute
    errors = import_mdl2.load(self, context, **keywords)
  File "C:\Users\Affaf\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\cobra-blender\import_mdl2.py", line 351, in load
    data = load_mdl2(filepath)
  File "C:\Users\Affaf\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\cobra-blender\import_mdl2.py", line 42, in load_mdl2
    data.read(stream, data, file=file_path)
  File "C:\Users\Affaf\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\cobra-blender\pyffi_ext\formats\ms2\__init__.py", line 243, in read
    model.populate(self, ms2_stream, self.start_buffer2, self.bone_names, base)
  File "C:\Users\Affaf\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\cobra-blender\pyffi_ext\formats\ms2\__init__.py", line 672, in populate
    self.read_verts(ms2_stream, self.data)
  File "C:\Users\Affaf\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\cobra-blender\pyffi_ext\formats\ms2\__init__.py", line 460, in read_verts
    self.update_dtype()
  File "C:\Users\Affaf\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\cobra-blender\pyffi_ext\formats\ms2\__init__.py", line 454, in update_dtype
    raise AttributeError(f"Vertex size for flag {self.flag} is wrong! Collected {self.dt.itemsize}, got {self.size_of_vertex}")
AttributeError: Vertex size for flag 853 is wrong! Collected 16, got 48

location: <unknown location>:-1

Game: Planet Zoo
Game Version: 1.0
Cobra Tools Release:  1.5.4
Cobra Blender Plugin: 1.5.1
Blender Version: 2.83.6

**Comment by HENDRIX-ZT2** [comment]
Which file?
