### ISSUE TITLE
Issues running the olv tool

### ISSUE THREAD

**Issue by JamesCuster** [OpenNaja/cobra-tools#67]
Hi, I'm not super familiar with python, and I am having trouble getting the tool to launch. There seems to be some issue interacting with the `piffy` package. Here is the traceback. Any help would be appreciated.

```
(base) C:\Users\Owner>python C:\Users\Owner\Documents\cobra-tools\cobra-tools\ovl_tool_gui.py
Traceback (most recent call last):
  File "C:\Users\Owner\Anaconda3\lib\site-packages\pyffi\object_models\xml\__init__.py", line 418, in startElement
    tag = self.tags[name]
KeyError: 'token'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Owner\Anaconda3\lib\site-packages\pyffi\object_models\xml\__init__.py", line 421, in startElement
    tag = self.tags_niftools[name]
KeyError: 'token'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Owner\Documents\cobra-tools\cobra-tools\ovl_tool_gui.py", line 8, in <module>
    from pyffi_ext.formats.ovl import OvlFormat
  File "C:\Users\Owner\Documents\cobra-tools\cobra-tools\pyffi_ext\formats\ovl\__init__.py", line 47, in <module>
    from pyffi_ext.formats.ms2 import Ms2Format
  File "C:\Users\Owner\Documents\cobra-tools\cobra-tools\pyffi_ext\formats\ms2\__init__.py", line 58, in <module>
    class Ms2Format(pyffi.object_models.xml.FileFormat):
  File "C:\Users\Owner\Anaconda3\lib\site-packages\pyffi\object_models\xml\__init__.py", line 106, in __init__
    parser.parse(xml_file)
  File "C:\Users\Owner\Anaconda3\lib\xml\sax\expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "C:\Users\Owner\Anaconda3\lib\xml\sax\xmlreader.py", line 125, in parse
    self.feed(buffer)
  File "C:\Users\Owner\Anaconda3\lib\xml\sax\expatreader.py", line 217, in feed
    self._parser.Parse(data, isFinal)
  File "..\Modules\pyexpat.c", line 414, in StartElement
  File "C:\Users\Owner\Anaconda3\lib\xml\sax\expatreader.py", line 333, in start_element
    self._cont_handler.startElement(name, AttributesImpl(attrs))
  File "C:\Users\Owner\Anaconda3\lib\site-packages\pyffi\object_models\xml\__init__.py", line 423, in startElement
    raise XmlError("error unknown element '%s'" % name)
pyffi.object_models.xml.XmlError: error unknown element 'token'
```

**Comment by HENDRIX-ZT2** [comment]
You did not install the required pyffi version.
The current version of the tools no longer needs pyffi - just download this: https://github.com/OpenNaja/cobra-tools/archive/master.zip
