### ISSUE TITLE
Jurassic.World.Evolution Blend Import mdl2 error!

### ISSUE THREAD

**Issue by byshiyi** [OpenNaja/cobra-tools#96]
Traceback (most recent call last):
  File "C:\Users\liaowang\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\cobra-tools-master\__init__.py", line 91, in execute
    errors = import_mdl2.load(self, context, **keywords)
  File "C:\Users\liaowang\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\cobra-tools-master\plugin\import_mdl2.py", line 31, in load
    data.load(filepath)
  File "C:\Users\liaowang\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\cobra-tools-master\generated\formats\ms2\__init__.py", line 364, in load
    eof = super().load(filepath)
  File "C:\Users\liaowang\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\cobra-tools-master\generated\io.py", line 260, in load
    self.read(stream)
  File "C:\Users\liaowang\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\cobra-tools-master\generated\formats\ms2\compound\Mdl2InfoHeader.py", line 82, in read
    self.model_info = stream.read_type(CoreModelInfo)
  File "C:\Users\liaowang\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\cobra-tools-master\generated\io.py", line 200, in read_type
    obj.read(self)
  File "C:\Users\liaowang\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\cobra-tools-master\generated\formats\ms2\compound\CoreModelInfo.py", line 55, in read
    self.bounds_min = stream.read_type(Vector3)
  File "C:\Users\liaowang\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\cobra-tools-master\generated\io.py", line 200, in read_type
    obj.read(self)
  File "C:\Users\liaowang\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\cobra-tools-master\generated\formats\ms2\compound\Vector3.py", line 26, in read
    self.x = stream.read_float()
  File "C:\Users\liaowang\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\cobra-tools-master\generated\io.py", line 158, in read_value
    return unpack(read(size))[0]
struct.error: unpack requires a buffer of 4 bytes

location: <unknown location>:-1

How should I solve this problem? I have strictly followed the way you explained!

**Comment by HENDRIX-ZT2** [comment]
Model must have been extracted with precisely the same tools version that you use to import into blender.
