### ISSUE TITLE
help Introduce errors 

### ISSUE THREAD

**Issue by byshiyi** [OpenNaja/cobra-tools#99]
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\scripts\addons\cobra-tools-master\__init__.py", line 91, in execute
    errors = import_mdl2.load(self, context, **keywords)
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\scripts\addons\cobra-tools-master\plugin\import_mdl2.py", line 34, in load
    b_armature_obj = import_armature(data)
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\scripts\addons\cobra-tools-master\plugin\modules_import\armature.py", line 32, in import_armature
    armature_name = bone_names[0]
IndexError: list index out of range

location: <unknown location>:-1

**Comment by HENDRIX-ZT2** [comment]
Which file? Which game? Latest tools?

**Comment by byshiyi** [comment]
Game：Jurassic.World.Evolution   

The latest tools：https://github.com/OpenNaja/cobra-tools/archive/master.zip

**Comment by HENDRIX-ZT2** [comment]
> While model file??

**Comment by byshiyi** [comment]
You can try
Url:https://drive.google.com/file/d/1zOad7tRuEmBFXGH2BEn6p7aaoa6yrLNO/view?usp=sharing

**Comment by HENDRIX-ZT2** [comment]
Can't access the file, it's private.
